services:
- type: pserv
  name: openvscode-server
  env: docker
  autoDeploy: false
  disk:
    name: data
    mountPath: /home/workspace
    sizeGB: 1
- type: web
  name: oauth2-proxy
  env: docker
  dockerfilePath: Dockerfile.oauth2-proxy  
  autoDeploy: false
  envVars:
    - key: OPENVSCODE_HOSTPORT
      fromService:
        name: openvscode-server
        type: pserv
        property: hostport 
  # Use placeholders for sensitive data to allow Client information to be entered securely in the Render dashboard
    - key: OAUTH2_PROXY_CLIENT_ID
      sync: false
    - key: OAUTH2_PROXY_CLIENT_SECRET
      sync: false
    - key: OAUTH2_PROXY_PROVIDER
      sync: false
